### PR TITLE
Metanull Validators and Client Selection

### PR DESCRIPTION
**Pull request by metanull-operator**
Initial client selection for Metanull and 1000 validator keys. First 20 keys submitted through launchpad during 138.

### CODE REVIEW

**Comment by metanull-operator** [comment]
Looks like CoinCashew beat me to claim Teku/Besu by 2 hours. I can change clients if necessary.

**Comment by taxmeifyoucan** [comment]
Thanks a lot for the PR, all looks good! 
Regarding the pair, indeed CoinCashew beat you to it :) Would you mind swapping one of the clients? For example Lodestar also supports Ephemery natively if that's easier for you. Plenty of empty options there!

**Comment by metanull-operator** [comment]
I can switch but I have not had good luck with Lodestar (or Lighthouse) in the past. I might be willing to give Lodestar another try but I only recently gave up on Lighthouse. I'll figure out which clients I'm comfortable with.

Too bad too because I spent a good amount of time automating my setup around Ephemery Teku/Besu and then ran into a bug with the ethStaker-deposit-cli that delayed me a couple hours. It will probably be a couple of days until I can do the same for another pair, but I'll get on it.

I

**Comment by metanull-operator** [comment]
Any problem with me claiming a pair before I get them up and running?

**Comment by taxmeifyoucan** [comment]
Sorry about the confusion with different clients! If you cannot make other pair work, feel free too keep it like this. Keep in mind that the incentive program allows for running multiple combos for extra reward. 

We tried many different setups in the past and didn't run into any major issues. The goal of the program is to run every client pair and deploy more combos on the network so it's strongly preferred.

**Review by taxmeifyoucan — APPROVED** [review]

**Review by pk910 — APPROVED** [review]

**Comment by pk910** [comment]
Heya @metanull-operator,
Looks all good and happy to merge :)

Can you confirm that you've imported all keys to your VC, so they'll be active after the reset?
And also, that your node is set up in a way that follows the reset schedule automatically?

**Pull request merged**
